g59/nestjs-plugins

- .github/mergeable.yml
- README.md
- example/nest-cli.json
- example/package.json
- example/src/app.controller.spec.ts
- example/src/app.controller.ts
- example/src/app.module.ts
- example/src/app.service.ts
- example/src/main.ts
- example/tsconfig.build.json
- example/tsconfig.json
- lerna.json
- nest-cli.json
- package.json
- yarn.lock
> chore: Added example

- .github/workflows/nodejs.yml
- README.md
> chore: Added coveralls

- .github/workflows/nodejs.yml
> chore: use default options

- example/package.json
- lerna.json
- package.json
- yarn.lock
> fix: needs can-npm-publish

- .gitignore
- README.md
- packages/nestjs-graphql-relay/README.md
> chore: Added badge

- example/src/schema.gql
- packages/nestjs-graphql-relay/package.json
- packages/nestjs-slack-webhook/package.json
> fix: use MIT licence

- example/package.json
- lerna.json
- packages/nestjs-firebase/package.json
- packages/nestjs-graphql-relay/package.json
- packages/nestjs-slack-webhook/package.json
> Bump v1.0.0

- .github/mergeable.yml
- example/package.json
- lerna.json
- packages/nestjs-firebase/package.json
- packages/nestjs-graphql-relay/package.json
- packages/nestjs-slack-webhook/package.json
- Added peerDependencies
- diff https://github.com/g59/nestjs-plugins/compare/v1.0.0...release
> Bump v1.0.1

- example/package.json
- lerna.json
- packages/nestjs-firebase/package.json
- packages/nestjs-graphql-relay/package.json
- packages/nestjs-slack-webhook/package.json
oops ~ https://github.com/abyssparanoia/application-boilerplate/pull/67
> Bump v1.0.2

- .github/workflows/nodejs.yml
https://github.com/marketplace/actions/coveralls-github-action?version=v1.0.1#standard-example
> fix: github_token

- package.json
- packages/nestjs-graphql-relay/__tests__/index.test.ts
related https://github.com/typeorm/typeorm/issues/6107
> fix: query

- example/package.json
- yarn.lock
> fix: remove example type

- example/package.json
- package-lock.json
> fix: package version

- CHANGELOG.md
- example/package.json
- lerna.json
- packages/nestjs-firebase/package.json
- packages/nestjs-graphql-relay/package.json
- packages/nestjs-slack-webhook/package.json
- packages/nestjs-zendesk/package.json
- `nestjs-graphql-relay`, `nestjs-zendesk`
- [#632](https://github.com/g59/nestjs-plugins/pull/632) feat: add nestjs-zendesk module ([@9renpoto](https://github.com/9renpoto))
- Keisuke Kan ([@9renpoto](https://github.com/9renpoto))
> Bump v1.2.0

- CHANGELOG.md
- example/package.json
- lerna.json
- package-lock.json
- package.json
- packages/nestjs-firebase/package.json
- packages/nestjs-graphql-relay/package.json
- packages/nestjs-slack-webhook/package.json
- packages/nestjs-zendesk/package.json
- `nestjs-firebase`, `nestjs-graphql-relay`, `nestjs-slack-webhook`
- [#864](https://github.com/g59/nestjs-plugins/pull/864) chore: upgrade @nestjs v8 ([@9renpoto](https://github.com/9renpoto))
- Keisuke Kan ([@9renpoto](https://github.com/9renpoto))
> Bump v8.0.0

- package-lock.json
- package.json
- packages/nestjs-firebase/src/firebase.decorator.ts
- packages/nestjs-firebase/src/firebase.interface.ts
- packages/nestjs-firebase/src/firebase.module.spec.ts
- packages/nestjs-firebase/src/firebase.module.ts
- packages/nestjs-firebase/src/index.ts
- packages/nestjs-firebase/src/util/getFirebaseAdmin.ts
- packages/nestjs-graphql-relay/__tests__/index.test.ts
- packages/nestjs-graphql-relay/src/connectionArgs.ts
- packages/nestjs-graphql-relay/src/index.ts
- packages/nestjs-graphql-relay/src/orderBy.input.ts
- packages/nestjs-graphql-relay/src/pageInfo.ts
- packages/nestjs-slack-webhook/__tests__/injectSlack.test.ts
- packages/nestjs-slack-webhook/__tests__/slackModule.test.ts
- packages/nestjs-slack-webhook/src/createSlackProvider.ts
- packages/nestjs-slack-webhook/src/index.ts
- packages/nestjs-slack-webhook/src/slackCoreModule.ts
- packages/nestjs-slack-webhook/src/slackModule.ts
- packages/nestjs-zendesk/src/zendesk.module.spec.ts
- packages/nestjs-zendesk/src/zendesk.module.ts
- export firebase-admin storage
- sort imports
> feat: export firebase admin storage

- package.json
- packages/nestjs-firebase/__tests__/getFirebaseAdmin.test.ts
- packages/nestjs-firebase/src/util/getFirebaseAdmin.ts
> fix: nullable firebase options

- lerna.json
- package-lock.json
- packages/nestjs-firebase/package.json
- packages/nestjs-graphql-relay/package.json
- packages/nestjs-slack-webhook/package.json
- packages/nestjs-zendesk/package.json
related https://github.com/g59/nestjs-plugins/issues/1178
> Bump v8.2.2

- .github/workflows/npm-publish-packages.yml
https://github.com/g59/nestjs-plugins/actions/runs/2064850361
> fix: need build

- lerna.json
- package-lock.json
- packages/nestjs-firebase/package.json
- packages/nestjs-graphql-relay/package.json
- packages/nestjs-slack-webhook/package.json
- packages/nestjs-zendesk/package.json
closes https://github.com/g59/nestjs-plugins/issues/945
- fix: add peerDeps
- Bump v8.2.3
> fix: add @nestjs/common

- packages/nestjs-firebase/src/firebase.interface.ts
- packages/nestjs-firebase/src/util/getFirebaseAdmin.ts
related https://github.com/g59/nestjs-plugins/pull/1274
> refactor: rename firebase.db to firebase.firestore

- example/package.json
- package-lock.json
- package.json
- packages/nestjs-firebase/package.json
- packages/nestjs-graphql-relay/package.json
- packages/nestjs-slack-webhook/package.json
- packages/nestjs-zendesk/package.json
closes https://github.com/g59/nestjs-plugins/issues/1583 https://github.com/g59/nestjs-plugins/issues/1587
> Bump v10.0.0

- packages/nestjs-firebase/src/firebase.interface.ts
- packages/nestjs-firebase/src/util/getFirebaseAdmin.ts
> chore: firebase ability to use Realtime Database

- .github/workflows/bump.yml
Reverts g59/nestjs-plugins#1729
> Revert "fix(.github): rename branches"

- .github/workflows/dependabot.yml
auto merge patch update dependencies
> feat: add auto approve step
